microsoft/vscode-extension-telemetry

lib/telemetryReporter.d.ts, lib/telemetryReporter.js, src/telemetryReporter.ts
This is a possible fix for #18
I am still not able to repro #18, but the fix in this PR can go in nevertheless.
=> instantiate appinsights only if user has opt in

README.md
also added reference to "instrumentation key"
=> added link to setup guide

test/baseTelemetryAppender.test.ts, test/util.test.ts
Forgot some Microsoft copyright headers
=> Add forgotten Microsoft copyright

.github/workflows/pr-chat.yml
Adds the automatic PR code review chat bot
=> Add PR Chat

README.md
Adds the new extension guidelines to README
=> Add telemetry guideline link to readme

README.md
Had to dig deep to find this info.
=> Explain key is not sensitive and may be hardcoded

package-lock.json, package.json
Bumps package.json to prepare to release new module
=> Bump package version for release

src/common/baseTelemetryReporter.ts
This will fix https://github.com/microsoft/vscode-extension-telemetry/issues/123
=> Improve the email regex

package-lock.json, package.json
Bump packages to clear dependabot
=> Bump packages for dependabot

.npmignore
=> Exclude `.map` files from package

injectVersion.js, package.json, src/browser/telemetryReporter.ts, src/common/baseTelemetryAppender.ts, src/common/baseTelemetryReporter.ts, src/common/util.ts, src/node/telemetryReporter.ts, test/baseTelemetryAppender.test.ts, vscode.proposed.telemetryLogger.d.ts
Telemetry API surface has changed so this updates as well to stay inline with that.
=> Update to using latest telemetry API

dist/telemetryReporter.d.ts, package-lock.json, package.json, src/browser/telemetryReporter.ts, src/common/1dsClientFactory.ts, src/common/baseTelemetryReporter.ts, src/common/baseTelemetrySender.ts, src/node/telemetryReporter.ts, test/baseTelemetrySender.test.ts, vscode.proposed.telemetryLogger.d.ts
Updates the extension telemetry module to work with latest name changes in the API surface.
=> Update package due to API changes

package-lock.json, package.json, src/browser/telemetryReporter.ts
Fixes https://github.com/microsoft/vscode-extension-telemetry/issues/144
=> Fix double initialize

package-lock.json, package.json, src/browser/telemetryReporter.ts, src/browser/tsconfig.json
Fixes https://github.com/microsoft/vscode-extension-telemetry/issues/146
=> Switch to using `userAgentData` where available

dist/telemetryReporter.d.ts, package-lock.json, package.json, src/common/baseTelemetryReporter.ts
Adds an event listener for the telemetry level since the new telemetry API hides this internally and we wrap that API.
=> Add an event listener for telemetry level

dist/telemetryReporter.d.ts, src/common/baseTelemetryReporter.ts
Fixes https://github.com/microsoft/vscode-extension-telemetry/issues/171
=> Fix send raw telemetry

package-lock.json, package.json
=> Update packages to address security vuln

src/node/telemetryReporter.ts
Handles network errors when sending the request payload
=> Handle network errors sending the request

package-lock.json, package.json, src/common/baseTelemetrySender.ts
Removes a flush that was already occurring in the dispose call.
Also updates the version
=> Remove unnecessary flush

src/common/1dsClientFactory.ts
Brings https://github.com/microsoft/vscode/pull/201010 to extensions.
=> fix: add opt-out flag

package.json
Verification build https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259762&view=results
=> chore: fix APIScan build

src/common/appInsightsClientFactory.ts
=> Accept instrumentation and connection string

dist/telemetryReporter.d.ts, package-lock.json, package.json, src/browser/telemetryReporter.ts, src/common/baseTelemetryReporter.ts, src/node/telemetryReporter.ts
Fix https://github.com/microsoft/vscode-extension-telemetry/issues/228
=> Surface initialization options
