- package.json
- src/telemetryReporter.ts
- typings_patches/applicationinsights/index.d.ts
Since late February the extension telelmetry pipeline is seeing events like the below
Root cause: When we upgraded to use `0.18.0` version of appinsights SDK, it had this extra feature of collecting "dependency events" which we hadnt disabled
> Stop collecting dependency events

- README.md
They seem to be left over from c1a86de2344f425a779f759ef5d185626cf37a86.
> Remove SQM properties from README

- lib/telemetryReporter.d.ts
- lib/telemetryReporter.js
- src/telemetryReporter.ts
Log telemetry events to file when in verbose mode
Related to https://github.com/Microsoft/vscode/issues/54001
- VSCODE_LOGS has the path to the log folder form https://github.com/Microsoft/vscode/blob/e7058655de73b5a19a5b4286079ce68cb7c13523/src/vs/platform/environment/node/environmentService.ts#L211
- VSCODE_LOG_STACK tracks if verbose logging is enabled from https://github.com/Microsoft/vscode/blob/5fae91d61f12726e149fe5baed342eac2fbf8f88/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L144. But since this gets enabled for insiders all the time, this is not a great choice for the current scenario.
- [LogLevel](https://github.com/Microsoft/vscode/blob/1.25.1/src/vs/vscode.proposed.d.ts#L202-L206) is part of the proposed api. Once it makes it to stable, we can use …
> Log telemetry events to file when in verbose mode

- lib/telemetryReporter.d.ts
- lib/telemetryReporter.js
- src/telemetryReporter.ts
Extend the core telemetry package to include exception message types.  
The current model is that everything is an event and we need to ensure that exceptions from extension reflect the proper type.
> Extend the telemetryReporter to include exception message types.

- src/common/baseTelemetryReporter.ts
`vscode.env.isNewAppInstall` being a boolean disrupts the new `anonymizeFilePaths` function, as it expects all properties to be strings AFAIK.
```typescript
// sanitize with configured cleanup patterns
for (const regexp of cleanupPatterns) {
updatedStack = updatedStack.replace(regexp, "");
}
```
```typescript
/**
* Given an error stack cleans up the file paths within
* @param stack The stack to clean
* @param anonymizeFilePaths Whether or not to clean the file paths or anonymize them as well
* @returns The cleaned stack
*/
private anonymizeFilePaths(stack?: string, anonymizeFilePaths?: boolean): string {
```
```
[2021-08-22 11:25:23.651] [exthost] [error] TypeError: updatedStack.replace is not a function
at TelemetryReporter.anonymizeFilePaths …
```
> Add safer common property assignment for bool

- src/node/telemetryReporter.ts
This is a follow-up to https://github.com/microsoft/vscode-extension-telemetry/commit/1bd0f0cf1ccd1e584ef70f2e5aa95f028e9276d4 and https://github.com/microsoft/vscode-extension-telemetry/pull/57 respectively.
It seems that in my original PR I made the mistake of either picking the wrong tag name and/or misinterpreting the results of my testing in AppInsights UI.
Either way the library still collects the hostname under `cloudRoleInstance` (prior to this patch).
I left the original override for `cloudRole` there as `Visual Studio Code` still seems more relevant than `Web` in this context.
> node: Avoid collecting user hostnames

- src/browser/telemetryReporter.ts
- src/common/baseTelemetryReporter.ts
- src/node/telemetryReporter.ts
As ARM CPUs are gaining more traction I think it would be useful to track the architecture in addition to OS as a common property.
> common: Collect architecture as a common property

- lib/telemetryReporter.d.ts
- src/browser/telemetryReporter.ts
- src/common/baseTelemetryReporter.ts
- src/common/util.ts
- src/node/telemetryReporter.ts
For node application insights clients, there is a new constructor
parameter that allows users to pass a list of replacement options.
Each option includes a lookup regular expression and a replacement
string.
For each key in the base data or the envelope that matches the
lookup, the value will be replaced with the associated string. If
the value is undefined, then the key will be deleted.
Note that this only adds replacements for node clients as I did not
see an easy way to implement the same in web clients.
Fixes https://github.com/microsoft/vscode-extension-telemetry/issues/55
I have tested this in my own application and it is behaving as expected. However, I do not know how to regenerate the typings appropriately. Also, I still need to update some documentation to describe the new …
> Add ReplacementOptions to filter telemetry events

- lib/telemetryReporter.d.ts
- src/browser/telemetryReporter.ts
- src/common/baseTelemetryAppender.ts
- src/common/baseTelemetryReporter.ts
Better fix for https://github.com/microsoft/vscode-jupyter/issues/9218
Occasionally users of the module may want to send telemetry in development environments, test environments, or other heavily controlled environments in which VS code says telemetry is off but the developers know it is safe to send. This introduces some "unsafe" (I call them dangerous) functions which ignore the telemetry setting. Of course this should never be used in a shipped extension and is meant for controlled environments only.
/cc @amunger
> Adds support for sending telemetry in a test environment

- package-lock.json
- package.json
- test/baseTelemetryAppender.test.ts
This adds tests using sinon spys to the common appender layer. This requires a bit of casting and a few ts-ignores for spying on internal properties and using the sinon library. If anyone has any better ideas on how to do this with less of that please let me know.
> Add tests to the common appender

- README.md
I noticed the URL for the Application Insights guide at the top of the README was pointing to https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs-quick-start which doesn't seem to exist anymore, and would therefore redirect to https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core which made it very confusing to figure out what steps to take.
> Fix Application Insights Guide's URL

- src/common/baseTelemetryReporter.ts
A large refactor of the way sending telemetry events worked led to the loss of the extension prefix when sending an error event. 
This fixes #104
> Fix missing extension name in latest package.

- lib/telemetryReporter.d.ts
- package-lock.json
- package.json
- src/common/baseTelemetryReporter.ts
Error props used to be a compliance issue but no longer seem needed and cause lots of confusion. This PR removes them in one of our very few breaking changes to the .d.ts so people are aware of this.
> Remove error props

- src/common/baseTelemetryReporter.ts
The first party pipeline doesn't appear to play well with empty property or measurement bags. This insures that these bags are populated
> Fix empty props and measurements in pipeline

- .esbuild.config.js
- package-lock.json
- package.json
- src/browser/telemetryReporter.ts
- src/node/telemetryReporter.ts
First party extensions should no longer use App Insights.
1. This now throws a warning when AIF keys are used
2. We now do not bundle any node modules together and instead just bundle the source code
> Remove first party support of AI

- build/azure-pipelines/pipeline.yml
The package is smoke tested locally and therefore no need to get another approval prior to publishing.
> Skip pre-publish approval

- .npmignore
- package-lock.json
- package.json
We can ignore the proposed.d.ts and the prepack script after it's packaged.
> Ignore a few more unnecessary files in the bundle

- dist/telemetryReporter.d.ts
- package-lock.json
- package.json
- src/common/baseTelemetryReporter.ts
- src/common/baseTelemetrySender.ts
Fixes #152
After further investigation both 1DS and App insights on the web don't support the `trackException` function which makes the experience different for consumers based on telemetry system and architecture it's being run on. The point of this module was to abstract away these differences and to allow for a unified experience. I've decided to remove the ability to log a raw exception and instead it will be up to consumers to break the error object down ito a set of properties and send it via the `sendTelemetryErrorEvent`. This allows them to specify their chosen name without the module making any assumptions about their specific telemetry needs.
Unfortunately this is a breaking change.
> Removes the ability to log a raw exception from the module

- src/common/1dsClientFactory.ts
We were unloading the 1DS client, but not flushing the buffer.
> Better handle teardown of 1DS client

- package-lock.json
- package.json
- src/common/baseTelemetrySender.ts
Don't throw an error in `sendErrorData`
> Don't throw error in sendErrorData

- src/browser/telemetryReporter.ts
- src/common/1dsClientFactory.ts
- src/common/baseTelemetryReporter.ts
- src/common/baseTelemetrySender.ts
- src/node/telemetryReporter.ts
- test/baseTelemetrySender.test.ts
Separates out the logic from flushing to the logic of dispose. Also makes it so that if you await the disposal of the reporter we will properly await flushing it
> More disposal / flush logic

- .github/workflows/node.js.yml
Appears node 12 doesn't work with optional chaining and is well beyond EOL.
> Drop support for node 12 in CI

- package-lock.json
- package.json
Use a VS Code type version that matches the engine version to avoid any unsuspecting breaking changes caused by later API.
> Use VS code types that match the engine

- src/common/baseTelemetryReporter.ts
Fixes: https://github.com/microsoft/vscode-extension-telemetry/issues/181
Fixes an issues found by the Copilot data science team 
cc @yemohyleyemohyle
> Send the value assigned to the telemetry property key not the property key itself

- src/browser/telemetryReporter.ts
- src/common/1dsClientFactory.ts
- src/node/telemetryReporter.ts
Shorten the teardown time and make it synchronous. Also skip calling flush as unload will do just that.
Hopefully helps with https://github.com/microsoft/vscode/issues/192742
> Less time for teardown

- package-lock.json
- package.json
- src/browser/telemetryReporter.ts
- src/browser/tsconfig.json
- src/common/appInsightsClientFactory.ts
- src/common/baseTelemetryReporter.ts
- src/node/telemetryReporter.ts
- src/node/tsconfig.json
Use XHR override with the web SDK to allow for removing the node app insights SDK and reduce the bundle size.
> Use web basic SDK for both node + web to reduce bundle size

- build/azure-pipelines/pipeline.yml
Tests now fail on Node 14. Node 14 and Node 16 are EOL. Node 18 and 20 are LTS so we will test against them
> Remove Node 14, and 16 from test matrix. Add Node 18 and Node 20

- src/common/baseTelemetrySender.ts
- test/baseTelemetrySender.test.ts
Hey, I'm using this package and noticed that all unhandled errors reported by it don't have any common properties (like extension or vscode versions).
It seems like `sender.sendErrorData` doesn't always receive data objects with the `properties` field, in which case common properties that the vscode usually supplies to all events or errors will not be sent.
In the case of unhandled errors vscode itself [calls `sender.sendErrorData` method](https://github.com/microsoft/vscode/blob/a344f294ce1bdb1cefe667488427ce487565b1c6/src/vs/workbench/api/common/extHostTelemetry.ts#L293) providing the data object without `properties` field. 
Internally (and publicly through TelemetryLogger extension API) vscode seem to always treat `data` argument as `Record<string, any>` type. It acknowledges that …
> Improve properties capture for the sendErrorData method

- src/common/appInsightsClientFactory.ts
If not supplied to the constructor the delegate AppInsightsCore class does not pick up the default channel (`BreezeChannelIdentifier = "AppInsightsChannelPlugin"`) plugin configuration and therefore doesn't use the supplied XHR override.
This is subtle to notice when running in Node 18+ (VS Code 1.82+) since the AppInsights SDK mostly uses the `fetch` API which is available in Node and appears to work.
This is similar to the pattern used for the 1DS client which presumably doesn't have the same issue and is where I got the idea to try it. Except the 1DS SDK separates the constructor from an `initialize` method:
https://github.com/microsoft/vscode-extension-telemetry/blob/3a87442dc26f80072f793ac8a1fc47bf0224c81a/src/common/1dsClientFactory.ts#L50
> Set xhr override before creating AppInsights client

- src/browser/telemetryReporter.ts
Thanks for the library! We use this a lot, and are very happy with its implementation.
This PR aims to replace the usage of the [deprecated `navigator.appVersion`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion) with a cleaned `userAgent` string, in the case where `userAgentData` is unavailable (all non-chromium browsers, including Safari and Firefox).
> Use clean user agent string instead of `appVersion` when `userAgentData` is unavailable.

- package-lock.json
- package.json
- src/common/1dsClientFactory.ts
Rollback some telemetry packages due to
https://github.com/microsoft/ApplicationInsights-JS/issues/2311
and
https://github.com/microsoft/ApplicationInsights-JS/issues/2306
and
https://github.com/microsoft/ApplicationInsights-JS/issues/2307
> Rollback packages

- README.md
- dist/telemetryReporter.d.ts
- src/browser/telemetryReporter.ts
- src/common/appInsightsClientFactory.ts
- src/common/util.ts
- src/node/telemetryReporter.ts
> Update readme + support connection string

- src/browser/telemetryReporter.ts
- src/common/appInsightsClientFactory.ts
- src/node/telemetryReporter.ts
This PR adds session ID metadata when reporting events.
Before this change, all events would be collected under a single session under Application Insights. It makes it hard to isolate reported events and reason how often users launch the extension.
In this PR, we use vscode's env `sessionId` field to pass it as session identifier when reporting app insight events (via `app.sesId` field).
> Propagate session ID metadata

- dist/telemetryReporter.d.ts
- package-lock.json
- package.json
- src/browser/telemetryReporter.ts
- src/node/telemetryReporter.ts
Makes it simpler to use this module as ESM and CJS
This should fix https://github.com/microsoft/vscode-extension-telemetry/issues/222
> No more default export for the TelemetryReporter
